**PyTorch with GPU in the Cloud**

To enable GPU usage go to Edit -> Notebook settings -> Hardware accelerator and select GPU


**Tensor**

In PyTorch a tensor is a multi-dimensional matrix of a single data-type:
* Scalar: single value
* Vector: list of values
* Matrix: two dimensional array
* Tensor: n-dimensional array



In [3]:
import torch

# sample tensor (1 dimension)
a = torch.rand(5)

# sample tensor (2 dimensions)
b = torch.zeros(3,3)

# sample tensor (5 dimension)
c = torch.ones(3,1,5,5,2)

print(a)
print(b)
print(c)

tensor([0.8443, 0.2280, 0.3084, 0.3882, 0.0135])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[[[[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]]]],



        [[[[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
   

**Enable GPU Usage with PyTorch**



In [4]:
if torch.cuda.is_available(): 
    device = torch.device('cuda') 
    print("GPU device is available")
else:                                                   
    device = torch.device('cpu') 
    print("GPU device is NOT available")


GPU device is available


In [5]:
# create PyTorch tensor
x = torch.rand(5, 5)

# attach tensor to GPU device
x = x.to(device)
print("Is tensor x on the GPU: {} ".format(x.is_cuda))
print(x)

Is tensor x on the GPU: True 
tensor([[0.8115, 0.8252, 0.2179, 0.4856, 0.9974],
        [0.3306, 0.9520, 0.7906, 0.0312, 0.7092],
        [0.3479, 0.6942, 0.9668, 0.0566, 0.6628],
        [0.1313, 0.1892, 0.3552, 0.4378, 0.2169],
        [0.9014, 0.9173, 0.5124, 0.2220, 0.5867]], device='cuda:0')


In [0]:
# can also attach PyTorch Neural Network modules from torch.nn to GPU

import torch.nn as nn
import torch.nn.functional as F

class NeuralNetwork(nn.Module):
    def __init__(self):
      super(NeuralNetwork, self).__init__()
      self.dense_layer_1 = nn.Linear(4, 32)
      self.dense_layer_2 = nn.Linear(32, 2)

    def forward(self, x):
      x = F.relu(self.dense_layer_1(x))
      return F.relu(self.dense_layer_2(x))

In [7]:
neural_net = NeuralNetwork().to(device)

print("Is neural network on the GPU: {} ".format(next(neural_net.parameters()).is_cuda))
print(neural_net)


Is neural network on the GPU: True 
NeuralNetwork(
  (dense_layer_1): Linear(in_features=4, out_features=32, bias=True)
  (dense_layer_2): Linear(in_features=32, out_features=2, bias=True)
)
