In [0]:
import torch

### torch.nn Module

In [0]:
import torch.nn as nn
import torch.nn.functional as F

In [3]:
# create simple Neural Network

class NeuralNetwork(nn.Module):
    def __init__(self, input_size, output_size, hidden_size):
        super(NeuralNetwork, self).__init__()
        # create fully connected layers
        self.dense_layer_1 = nn.Linear(input_size, hidden_size)
        self.dense_layer_2 = nn.Linear(hidden_size, hidden_size)
        # create output
        self.output = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        # use forward to construct the forward pass of the computational graph
        x = F.relu(self.dense_layer_1(x))
        x = F.relu(self.dense_layer_2(x))
        return self.output(x)

my_neural_network = NeuralNetwork(input_size=5, output_size=1, hidden_size=32)
print(my_neural_network)

NeuralNetwork(
  (dense_layer_1): Linear(in_features=5, out_features=32, bias=True)
  (dense_layer_2): Linear(in_features=32, out_features=32, bias=True)
  (output): Linear(in_features=32, out_features=1, bias=True)
)


### Gradients with Autograd

In [4]:
# create a tensor of ones
a = torch.ones(3, 3)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# enable gradient computaton
a.requires_grad = True
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [6]:
# perform operation on tensor a
b = a * 5 + 2
print(b)

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]], grad_fn=<AddBackward0>)


In [0]:
# perform operation on b
c = b.sum()

In [0]:
# compute gradients with .backward()
c.backward()

In [9]:
# print gradients of tensor a
print(a.grad)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])


### Loss and Optimizer

In [0]:
# import optimizer
import torch.optim as optim

In [0]:
# create neural network
my_neural_network = NeuralNetwork(input_size=5, output_size=1, hidden_size=32)

#create mean squared error loss function
loss_fn = nn.MSELoss()

# create Adam optimizer
optimizer = optim.Adam(my_neural_network.parameters())

# create data
input_data = torch.randn(32,5) 
target_data = input_data.sum(dim=1) * 10 - 2
target_data = target_data.view(-1,1)

In [12]:
# train network 1000 episodes
for i in range(1000):
    # feed input data into network and get neural network output
    neural_network_output = my_neural_network(input_data)
    # calculate loss on neural network output and target data
    loss = loss_fn(neural_network_output, target_data)
    # clear the accumulated gradients
    optimizer.zero_grad()
    # backpropagate the gradients
    loss.backward()
    # optimize the neural network parameters in the direction of the gradients
    optimizer.step()
    if i % 50 == 0:
        print("Episode {} Loss is {}".format(i,loss))

Episode 0 Loss is 380.24676513671875
Episode 50 Loss is 349.68511962890625
Episode 100 Loss is 241.99827575683594
Episode 150 Loss is 83.87288665771484
Episode 200 Loss is 13.128963470458984
Episode 250 Loss is 4.99954080581665
Episode 300 Loss is 2.396054744720459
Episode 350 Loss is 1.272779107093811
Episode 400 Loss is 0.841343104839325
Episode 450 Loss is 0.591335654258728
Episode 500 Loss is 0.4359842836856842
Episode 550 Loss is 0.3261908292770386
Episode 600 Loss is 0.24087171256542206
Episode 650 Loss is 0.17958860099315643
Episode 700 Loss is 0.1358397752046585
Episode 750 Loss is 0.10320333391427994
Episode 800 Loss is 0.07864130288362503
Episode 850 Loss is 0.060496605932712555
Episode 900 Loss is 0.04690361022949219
Episode 950 Loss is 0.03676452860236168
